### ISSUE TITLE
Please add this expansion: Equipment Expensive Item Color

### ISSUE THREAD

**Issue by githubgilhad** [OoliteProject/oolite-expansion-catalog#5]
**Which expansion shall be added?**

Give the the download url for the expansion.

https://wiki.alioth.net/img_auth.php/c/c6/Oolite.oxp.Gilhad.EquipmentExpensiveItemColor.oxz

Give the url to the thread discussing the new expansion on https://bb.oolite.space. That thread needs to tell everyone the name of the oxp, what to expect, where they can download, and that you’re looking for testers. That thread will then become the main place to discuss your mod going forward.

https://bb.oolite.space/viewtopic.php?p=298428#p298428

Wiki
https://wiki.alioth.net/index.php/Equipment_Expensive_Item_Color

**Comment by AnotherCommander** [comment]
Expansion added.
